### ISSUE TITLE
throw new Error('Dialect needs to be explicitly supplied as of v4.0.0');

### ISSUE THREAD

**Issue by QiZhongdd** [TaleLin/lin-cms-koa#38]
请问下install lin-mizar后运行报下面的错什么原因呢？

throw new Error('Dialect needs to be explicitly supplied as of v4.0.0');
      ^

Error: Dialect needs to be explicitly supplied as of v4.0.0
    at new Sequelize (/Users/zhongqi/Desktop/node+koa瑞商/node_modules/sequelize/lib/sequelize.js:265:13)
    at Object.<anonymous> (/Users/zhongqi/Desktop/node+koa瑞商/node_modules/lin-mizar/lin/db.js:27:14)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/zhongqi/Desktop/node+koa瑞商/node_modules/lin-mizar/lin/core.js:8:14)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/zhongqi/Desktop/node+koa瑞商/node_modules/lin-mizar/lin/index.js:4:22)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)

**Comment by JohnStream** [comment]
目前sequelize版本连接数据库需显示指定dialect字段以表示连接哪种类型的数据库。
`module.exports = {
  db: {
    database: 'lin-cms-koa',
    host: 'localhost',
    dialect: 'mysql',
    port: 3306,
    username: 'xxxx',
    password: 'xxxxx',
    logging: false,
    timezone: '+08:00'
  },
  secret: xxxxxx
};`
