### ISSUE TITLE
按照文档执行node tests/helper/add_super.js报错

### ISSUE THREAD

**Issue by KDWangBoss** [TaleLin/lin-cms-koa#42]
**描述 bug**

- 你是如何操作的？
> git clone git@github.com:TaleLin/lin-cms-koa.git
> yarn
> node app/starter.js

- 发生了什么？
>```
C:\Users\11705\Desktop\易米科技\Project\Project\官网(new)\源码\lin-cms-koa>node tests/helper/add_super.js
{ SequelizeValidationError: notNull Violation: user.username cannot be null
    at Promise.all.then (C:\Users\11705\Desktop\易米科技\Project\Project\官网(new)\源码\lin-cms-koa\node_modules\sequelize\lib\instance-validator.js:74:15)
    at tryCatcher (C:\Users\11705\Desktop\易米科技\Project\Project\官网(new)\源码\lin-cms-koa\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\11705\Desktop\易米科技\Project\Project\官网(new)\源码\lin-cms-koa\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Users\11705\Desktop\易米科技\Project\Project\官网(new)\源码\lin-cms-koa\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Users\11705\Desktop\易米科技\Project\Project\官网(new)\源码\lin-cms-koa\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Users\11705\Desktop\易米科技\Project\Project\官网(new)\源码\lin-cms-koa\node_modules\bluebird\js\release\promise.js:729:18)
    at Promise._fulfill (C:\Users\11705\Desktop\易米科技\Project\Project\官网(new)\源码\lin-cms-koa\node_modules\bluebird\js\release\promise.js:673:18)
    at PromiseArray._resolve (C:\Users\11705\Desktop\易米科技\Project\Project\官网(new)\源码\lin-cms-koa\node_modules\bluebird\js\release\promise_array.js:127:19)
    at PromiseArray._promiseFulfilled (C:\Users\11705\Desktop\易米科技\Project\Project\官网(new)\源码\lin-cms-koa\node_modules\bluebird\js\release\promise_array.js:145:14)
    at Promise._settlePromise (C:\Users\11705\Desktop\易米科技\Project\Project\官网(new)\源码\lin-cms-koa\node_modules\bluebird\js\release\promise.js:609:26)
    at Promise._settlePromise0 (C:\Users\11705\Desktop\易米科技\Project\Project\官网(new)\源码\lin-cms-koa\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Users\11705\Desktop\易米科技\Project\Project\官网(new)\源码\lin-cms-koa\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\Users\11705\Desktop\易米科技\Project\Project\官网(new)\源码\lin-cms-koa\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Users\11705\Desktop\易米科技\Project\Project\官网(new)\源码\lin-cms-koa\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\11705\Desktop\易米科技\Project\Project\官网(new)\源码\lin-cms-koa\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\11705\Desktop\易米科技\Project\Project\官网(new)\源码\lin-cms-koa\node_modules\bluebird\js\release\async.js:15:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
  name: 'SequelizeValidationError',
  errors:
   [ ValidationErrorItem {
       message: 'user.username cannot be null',
       type: 'notNull Violation',
       path: 'username',
       value: null,
       origin: 'CORE',
       instance: [user],
       validatorKey: 'is_null',
       validatorName: null,
       validatorArgs: [] } ] }
>```

**你使用哪个版本出现该问题？**
> master

**Comment by PedroGao** [comment]
出现这样的问题的大概率是mysql版本低了

**Comment by KDWangBoss** [comment]
mysql版本为： 8.0.15
node版本： v10.15.3
可以了，感谢答复
