### ISSUE TITLE
按步骤安装报错,lin-mizar/lin/config

### ISSUE THREAD

**Issue by freeheart** [TaleLin/lin-cms-koa#53]
stater.js第三行：const { config } = require('lin-mizar/lin/config');
执行报错：
internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module 'lin-mizar/lin/config'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (F:\wwwroot\cms\starter\app\starter.js:3:20)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)

**Comment by PedroGao** [comment]
看是否安装了最新版本，更新一下lin-mizar

**Comment by wangyuan0108** [comment]
lin-mizar 0.2.3安装报错；
![image](https://user-images.githubusercontent.com/22407253/69109912-0f947500-0ab4-11ea-9444-12435ebb1e23.png)

**Comment by PedroGao** [comment]
建议使用npm的官方源，淘宝的镜像会有延迟
